# Generated by Django 3.0.1 on 2020-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('descript', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
